ndk

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,3 +1,19 @@
+if test -n "$ngx_module_link"; then
+    if test -n "$NDK_SRCS"; then
+        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_http_json_module." 1>&2
+        exit 1
+    fi
+else
+    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_http_json_module." 1>&2
+        exit 1
+    fi
+fi
+
 ngx_addon_name=ngx_http_json_module
 if test -n "$ngx_module_link"; then
     ngx_module_type=HTTP
@@ -12,3 +28,5 @@ else
 HTTP_MODULES="$HTTP_MODULES $ngx_addon_name"
 NGX_ADDON_SRCS="$ngx_addon_dir/ngx_http_json_module.c"
 fi
+
+CFLAGS="$CFLAGS -DNDK_SET_VAR"
